---
- name: Install some packages
  hosts: all
  tasks:

# Wait until host is ready
    - name: Wait for {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }} host {{inventory_hostname}} connection
      wait_for_connection:

- name: Read in host & state details
  hosts: all

  tasks:
#
# Hardware
#
    - name: Discover hardware model according to device tree
      # RPi model strings end with null character which must be stripped
      ansible.builtin.shell: cat /proc/device-tree/model | rev | cut -c 1- | rev
      register: dt_hardware_model

    - name: Discover hardware serial number
      ansible.builtin.shell: cat /sys/firmware/devicetree/base/serial-number | rev | cut -c 1- | rev
      register: sys_serial_number
#
# Kernel state
#
      # is_config_mounted == 0 indicates configfs is mounted
    - name: Check if configfs is mounted
      ansible.builtin.shell: mountpoint /sys/kernel/config/
      register: is_configfs_mounted
#
# Device tree modules
#
#    - name: Check if module dwc2 is loaded
#      ansible.builtin.shell: lsmod | grep libcomposite
#      register: is_dwc2_loaded
#
# Kernel modules
#
    - name: Retrieve loaded modules
      ansible.builtin.shell: "lsmod | cut -f1 -d' '"
      register: modules_loaded
#
# Kernel modules
#
    - name: Check if libcomposite is loaded
      ansible.builtin.shell: lsmod
      register: is_libcomposite_loaded
#
# Display results
#
    - name: "Target {{ inventory_hostname }} report"
      debug:
        msg: 
        - "Hardware        - {{ dt_hardware_model.stdout }}"
        - "Architecture    - {{ ansible_architecture }}"
        - "Serial Number   - {{ sys_serial_number.stdout_lines }}"
        - "OS              - {{ ansible_distribution }} {{ ansible_distribution_major_version }} {{ ansible_distribution_release }} "
        - "cmdline modules - {{ ansible_cmdline['modules-load'] }}"
        - "{{ modules_loaded.stdout.split('\n') }}"
        - "configfs status - {{ is_configfs_mounted.stdout }}"
        - "ansible facts   - {{ ansible_facts | to_json }}"
#       - "device links    - {{ ansible_device_links['ids'] | to_nice_json }}"
#       - "devices         - {{ ansible_devices | to_json  }}"

    - name: Target model configfs - {{ is_configfs_mounted.stdout }}
      ansible.builtin.shell: echo

    - name: Check contents for emptiness
      debug:
        msg: "dwc2 module is not loaded"
      when: is_dwc2_loaded.stdout == ""

    - name: Check contents for non emptiness
      debug:
        msg: "dwc2 module is loaded"
      when: is_dwc2_loaded.stdout != ""

    - name: Check contents for emptiness
      debug:
        msg: "libcomposite module is not loaded"
      when: is_libcomposite_loaded.stdout == ""

    - name: Check contents for non emptiness
      debug:
        msg: "libcomposite module is loaded"
      when: is_libcomposite_loaded.stdout != ""
