all:
  vars:
    ansible_connection: ssh
    ansible_user: devuan
    ansible_password: devuan
    ansible_become: true
#   ansible_ssh_private_key_file: id_ed25519
    ansible_python_interpreter: /usr/bin/python3

  hosts:
    devuanpi.intern:
