---
- name: Install some packages
  hosts: all
  tasks:

# Wait until host is ready
   - name: Wait for host {{inventory_hostname}} connection
     wait_for_connection:
    
# Some useful packages for Devuan
   - name: install bind-utils for Debian derivative
     package:
       name: bind9utils
       state: present
     when: ansible_os_family == 'Debian'

   - name: install dnsmasq
     package:
       name: dnsmasq
       state: present

   - name: configure dnsmasq
     ansible.builtin.copy:
       src: etc/dnsmasq.d/usb.conf
       dest: /etc/dnsmasq.d/usb.conf

   - name: enable dnsmasq
     sysvinit:
       name: dnsmasq
       state: started
       enabled: yes

   - name: install htop
     package:
       name: htop
       state: present

   - name: install lsof
     package:
       name: lsof
       state: present


# DEBUG Clone Reflow repo
   - name: Clone devuan-pi-setup repository
     git:
       repo: https://github.com/adam-burns/devuan-pi-setup
       dest: devuan-pi-setup
       version: master
       clone: yes
       update: yes

# Add loading overlay module dwc2 to cmdline.txt
   - name: "Add loading overlay module dwc2 to cmdline.txt"
     become: yes
     become_user: root
     replace: 
       path: /boot/cmdline.txt
       # regexp: '^((?!modules-load=dwc2).)+$'
       regexp: '^(.*)rootwait$'
       replace: '\1 rootwait modules-load=dwc2'
       backup: no

   - name: Check if dtoverlay=dwc2 is present
     become: yes
     become_user: root
     lineinfile:
       state: absent
       path: "/boot/config.txt"
       regexp: "^dtoverlay=dwc2"
     check_mode: true
     changed_when: false # This just makes things look prettier in the logs
     register: check
   
   - name: Add dtoverlay=dwc2 if not present
     lineinfile:
       state: present
       path: "/boot/config.txt"
       line: "dtoverlay=dwc2"
     when: check.found == 0

   - name: Check if libcomposite module is configured in /etc/modules
     become: yes
     become_user: root
     lineinfile:
       state: absent
       path: "/etc/modules"
       regexp: "^libcomposite"
     check_mode: true
     changed_when: false # This just makes things look prettier in the logs
     register: check
   
   - name: Add libcomposite if not present
     lineinfile:
       state: present
       path: "/etc/modules"
       line: "libcomposite"
     when: check.found == 0

