---
- name: Install some packages
  hosts: all
  tasks:

# Wait until host is ready
    - name: Wait for {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_major_version'] }} host {{inventory_hostname}} connection
      wait_for_connection:

- name: Read in Host Details
  hosts: all

  tasks:

    - name: "Target {{ inventory_hostname }} report"
      debug:
        msg:
        - "Hardware             - {{ dt_hardware_model.stdout }}"
        - "Architecture         - {{ ansible_architecture }}"
        - "Serial Number        - {{ sys_serial_number.stdout_lines }}"
        - "OS                   - {{ ansible_distribution }} {{ ansible_distribution_major_version }} {{ ansible_distribution_release }} "
        - "cmdline modules-load - {{ ansible_cmdline['modules-load'] }}"
        - "configfs status      - {{ is_configfs_mounted.stdout }}"
        - "libcomposite module  - {{ is_libcomposite_loaded.stdout }}"
        - "dwc2 module          - {{ is_dwc2_loaded.stdout }}"
#       - "ansible facts   - {{ ansible_facts | to_json }}"
#       - "device links    - {{ ansible_device_links['ids'] | to_nice_json }}"
#       - "devices         - {{ ansible_devices | to_json  }}"
#       - "gadget_net_prefix    - {{ gadget_net_prefix }}"
#       - "random               - {{ 126 | random }}"

